version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db_env.yaml

  web:
    container_name: web
    build: .
#    restart: always
    ports:
      - "8072:8072"
    depends_on:
      - db
    env_file:
      - ./.env.yaml
